import { fullPaipan } from '../engine';
import type { TimeInput, QiGuaMethod, QiGuaBasis, CoreState, Synthesized } from '../types';
import { buildBaziPanel } from '../panels/bazi';
const $= (id: string) => document.getElementById(id);
const history: {id:number,label:string,input:TimeInput,method:QiGuaMethod,state:CoreState,synthesis:Synthesized}[] = [];
let snapshotId=0, activeTab='overview';
function setDefaultTime() { const now=new Date(); ['year','month','day','hour','minute'].forEach((id,i) => { const el=$(id) as HTMLInputElement; if(el) el.value=String([now.getFullYear(),now.getMonth()+1,now.getDate(),now.getHours(),now.getMinutes()][i]); }); }
function readForm() { const y=parseInt(($('year')?.value||'2000'),m=parseInt(($('month')?.value||'1'),d=parseInt(($('day')?.value||'1'),h=parseInt(($('hour')?.value||'12'); const method=($('method') as HTMLSelectElement)?.value as QiGuaMethod; const nums=($('nums') as HTMLInputElement)?.value.split(/[,\s]+/).map(Number).filter(n=>!isNaN(n))||[]; const basis=($('basis') as HTMLSelectElement)?.value as QiGuaBasis; return {input:{year:y,month:m,day:d,hour:h,minute:0} as TimeInput,method,numberInput:nums,basis}; }
function renderPanels(state:CoreState) { return '<section class="panel xiaoliu"><h2>小六壬</h2><div class="path">'+state.panels.xiaoliu.path.join(' → ')+'</div><div class="result '+state.panels.xiaoliu.result+'">'+state.panels.xiaoliu.result+'</div><p>'+state.panels.xiaoliu.meaning+'</p></section>' + '<section class="panel bazi"><h2>四柱</h2><div class="pillars">'+[state.bazi.year,state.bazi.month,state.bazi.day,state.bazi.hour].map((p,i) => '<div class="pillar"><div class="p-name">'+['年柱','月柱','日柱','时柱'][i]+'</div><div class="p-gz">'+p.ganzhi+'</div></div>').join('')+'</div></section>' + '<section class="panel meihua"><h2>梅花易数</h2><div class="triple"><div class="hex"><h3>'+state.panels.meihua.ben.fullName+'</h3></div><div class="hex"><h3>'+state.panels.meihua.hu.fullName+'</h3></div><div class="hex"><h3>'+state.panels.meihua.bian.fullName+'</h3></div></div><p>'+state.panels.meihua.interpretation+'</p></section>' + '<section class="panel zhouyi"><h2>周易</h2><p>本卦：'+state.panels.zhouyi.guaCi.ben+'</p><p>变卦：'+state.panels.zhouyi.guaCi.bian+'</p><p>'+state.panels.zhouyi.tuanZhuan+'</p></section>' + '<section class="panel liuyao"><h2>六爻</h2><p>'+state.panels.liuyao.summary+'</p></section>' + '<section class="panel synthesis"><h2>综合分析</h2><div class="trend '+state.panels.synthesis?.trend+'" style="display:none"></div></section>';
}
function addSnapshot(input:TimeInput,method:QiGuaMethod,state:CoreState,synthesis:Synthesized) { history.unshift({id:++snapshotId,label:`${input.year}/${input.month}/${input.day} ${input.hour}时[${method}]`,input,method,state,synthesis}); if(history.length>8) history.pop(); }
function renderCompareTable() { const el=$('compare-table') as HTMLTableElement; if(!el) return; if(history.length===0) { el.innerHTML='<tr><td>暂无记录</td></tr>'; return; } const headers=history.map(h=>'<th>'+h.label+'</th>').join(''); const rows=[ ['本卦',history.map(h=>h.state.hexagram.fullName], ['宫位',history.map(h=>h.state.hexagram.palace+'宫'], ['动爻',history.map(h=>h.moving.positions.join('、')||'无'], ['小六壬',history.map(h=>h.state.panels.xiaoliu.result], ['综合趋势',history.map(h=>h.synthesis?.trend||'')]].map(([key,vals])=>'<tr><td>'+key+'</td>'+vals.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join(''); el.innerHTML='<tr><th></th>'+headers+'</tr>'+rows; }
$('run-btn')?.addEventListener('click',()=>{ try{ const{input,method,numberInput,basis}=readForm(); const{state,synthesis}=fullPaipan(input,method,numberInput,0,undefined,basis); addSnapshot(input,method,state,synthesis); const out=$('output'); if(out) out.innerHTML=renderPanels(state); const sec=$('compare-section') as HTMLElement; if(sec) sec.style.display='block'; renderCompareTable(); }catch(e){ alert((e as Error).message); } });
if(document.readyState==='loading') window.addEventListener('DOMContentLoaded',setDefaultTime); else setDefaultTime();
