export function wuXingOf(ganOrZhi) { const m = { '甲': '木', '乙': '木', '丙': '火', '丁': '火', '戊': '土', '己': '土', '庚': '金', '辛': '金', '壬': '水', '癸': '水', '子': '水', '丑': '土', '寅': '木', '卯': '木', '辰': '土', '巳': '火', '午': '火', '未': '土', '申': '金', '酉': '金', '戌': '土', '亥': '水' }; return m[ganOrZhi] || ''; }
export function liuQinOf(zhiSelf, zhiOther, dayGan) { const selfEl = wuXingOf(zhiSelf), otherEl = wuXingOf(zhiOther); if (!selfEl || !otherEl)
    return ''; if (selfEl === otherEl)
    return wuXingOf(dayGan) === selfEl ? '比肩' : '比和'; const dayEl = wuXingOf(dayGan) || '木'; const rel = { '金': { '木': '财', '火': '官', '水': '食', '土': '印' }, '木': { '火': '食', '土': '财', '金': '官', '水': '印' }, '水': { '木': '印', '火': '财', '土': '官', '金': '食' }, '火': { '土': '印', '金': '财', '水': '官', '木': '食' }, '土': { '金': '印', '水': '官', '木': '财', '火': '食' } }; return (rel[dayEl] || {})[otherEl] || '和'; }
export function modOrMax(n, mod) { const r = n % mod; return r === 0 ? mod : r; }
export function buildBazi(y, m, d, h) { const sty = getSolarTermYear(y, m, d), sm = getSolarMonth(y, m, d), ygz = yearGZ(sty), mgz = monthGZ(ygz, sm), dgz = dayGZ(y, m, d), hgz = hourGZ(dgz, h); return { year: { gan: ygz[0], zhi: ygz[1], ganzhi: ygz }, month: { gan: mgz[0], zhi: mgz[1], ganzhi: mgz }, day: { gan: dgz[0], zhi: dgz[1], ganzhi: dgz }, hour: { gan: hgz.gz[0], zhi: hgz.gz[1], ganzhi: hgz.gz }, solarTermYear: sty, lunar: solarToLunar(y, m, d), solarTermNext: hourToDizhi(h) }; }
export function buildLines(hexIndex, moving, dayGan) { const h = getHexagramByIndex(hexIndex); const najiaStr = getNajia(TRIGRAMS[h.upper] || '', TRIGRAMS[h.lower] || ''); const parsed = parseNajia(najiaStr); return Array.from({ length: 6 }, (_, i) => { const pos = (i + 1); const isYang = h.lines[i] === true; const p = parsed[i]; return { position: pos, yinYang: (isYang ? 'yang' : 'yin'), changed: moving.includes(pos), tiangan: p?.gan || '甲', dizhi: p?.zhi || '子', shi: pos === h.shiPosition, ying: pos === h.yingPosition, liuQin: liuQinOf(p?.zhi || '', p?.zhi || '', dayGan) }; }); }
export function buildHexagram(hexIndex, moving, dayGan) { const h = getHexagramByIndex(hexIndex); return { index: hexIndex, name: h.name, fullName: h.fullName, upper: h.upper, lower: h.lower, palace: h.palace, element: h.element, nature: h.nature, lines: buildLines(hexIndex, moving, dayGan), shiPosition: h.shiPosition, yingPosition: h.yingPosition }; }
export function findChangedHexagram(hexIndex, moving) { const h = getHexagramByIndex(hexIndex); const changed = h.lines.map((b, i) => moving.includes(i + 1) ? !b : b); return findHexagramByTrigrams(bitsToTrigramIdx([changed[5], changed[4], changed[3]]), bitsToTrigramIdx([changed[2], changed[1], changed[0]])); }
export function findHuHexagram(hexIndex) { const h = getHexagramByIndex(hexIndex); return findHexagramByTrigrams(bitsToTrigramIdx([h.lines[4], h.lines[3], h.lines[2]]), bitsToTrigramIdx([h.lines[3], h.lines[2], h.lines[1]])); }
import { getHexagramByIndex, findHexagramByTrigrams, bitsToTrigramIdx, TRIGRAMS } from '../data/hexagrams.js';
import { getNajia, parseNajia, hourToDizhi } from '../data/najia.js';
import { yearGZ, monthGZ, dayGZ, hourGZ, getSolarMonth, getSolarTermYear, solarToLunar } from './calendar.js';
